[Interface]
# VPS Side - Link to Homelab
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = KEY_0
Table = off

# Web Ports (8808, 8809,22,8812)
PostUp = iptables -t nat -A PREROUTING -p tcp -m multiport --dports 8808,8809,22,8812 -j DNAT --to-destination 10.0.0.2
PostUp = iptables -A FORWARD -d 10.0.0.2 -p tcp -m multiport --dports 8808,8809,22,8812 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -d 10.0.0.2 -p tcp -m multiport --dports 8808,8809,22,8812 -j MASQUERADE

# GameServer Port (25565) - TCP & UDP
PostUp = iptables -t nat -A PREROUTING -p tcp --dport 25565 -j DNAT --to-destination 10.0.0.2:25565
PostUp = iptables -t nat -A PREROUTING -p udp --dport 25565 -j DNAT --to-destination 10.0.0.2:25565
PostUp = iptables -A FORWARD -d 10.0.0.2 -p tcp --dport 25565 -j ACCEPT
PostUp = iptables -A FORWARD -d 10.0.0.2 -p udp --dport 25565 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -d 10.0.0.2 -p tcp --dport 25565 -j MASQUERADE
PostUp = iptables -t nat -A POSTROUTING -d 10.0.0.2 -p udp --dport 25565 -j MASQUERADE

# --- POST-DOWN: CLEANUP ---
PostDown = iptables -t nat -D PREROUTING -p tcp -m multiport --dports 8808,8809,22,8812 -j DNAT --to-destination 10.0.0.2
PostDown = iptables -D FORWARD -d 10.0.0.2 -p tcp -m multiport --dports 8808,8809,22,8812 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -d 10.0.0.2 -p tcp -m multiport --dports 8808,8809,22,8812 -j MASQUERADE

PostDown = iptables -t nat -D PREROUTING -p tcp --dport 25565 -j DNAT --to-destination 10.0.0.2:25565
PostDown = iptables -t nat -D PREROUTING -p udp --dport 25565 -j DNAT --to-destination 10.0.0.2:25565
PostDown = iptables -D FORWARD -d 10.0.0.2 -p tcp --dport 25565 -j ACCEPT
PostDown = iptables -D FORWARD -d 10.0.0.2 -p udp --dport 25565 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -d 10.0.0.2 -p tcp --dport 25565 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -d 10.0.0.2 -p udp --dport 25565 -j MASQUERADE

[Peer]
# Homelab Peer
PublicKey = KEY_1
AllowedIPs = 10.0.0.2/24
