[Interface]
# VPS Side
Address = 10.10.10.1/24
ListenPort = 51821
PrivateKey = KEY_0
Table = off
MTU = 1280

PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -i %i -j ACCEPT


[Peer]
#Phone Peer
PublicKey = KEY_1
AllowedIPs = 10.10.10.2/32

[Peer]
#Laptop Peer
PublicKey = KEY_2
AllowedIPs = 10.10.10.3/32
